[package]
authors = ["Raphael Nestler <raphael.nestler@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "rfid-audio"
version = "0.1.0"

[dependencies]
cortex-m = "0.5.8"
cortex-m-semihosting = "0.3.3"
cortex-m-rtfm = "0.5.1"
embedded-mp3 = { version = "0.1.0", path = "../embedded-mp3" }
lazy_static = {version="1.4.0", features = ["spin_no_std"]}
panic-itm = "0.4.1"

[dependencies.stm32f3xx-hal]
features = ["stm32f303xc", "rt"]
version = "0.4.0"

# this lets you use `cargo fix`!
[[bin]]
name = "rfid-audio"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations

[profile.dev]
opt-level = 3
