[package]
authors = ["Raphael Nestler <raphael.nestler@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "hello-rtfm"
version = "0.1.0"

[dependencies]
cortex-m = "0.5.8"
cortex-m-rt = "0.6.5"
cortex-m-semihosting = "0.3.2"
panic-semihosting = "0.5.1"
cortex-m-rtfm = {git="https://github.com/japaric/cortex-m-rtfm.git"}


[dependencies.stm32f30x]
version = "0.8.0"
features= ["rt"]

# this lets you use `cargo fix`!
[[bin]]
name = "hello-rtfm"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
